# Generated by Django 2.0.5 on 2018-06-30 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=128)),
                ('expiry_date', models.DateField()),
                ('type_of_card', models.CharField(max_length=50)),
                ('cvv', models.IntegerField()),
                ('card_no', models.CharField(max_length=20)),
                ('name_on_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
